AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CloudFormation Demo
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lambda_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::022923077846:role/service-role/index-photos"
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lambda_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./search-photos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::022923077846:role/service-role/search-photos-role-7iomr6nq"
      Environment:
        Variables:
          REGION: us-east-1
